---
# Source: redis/templates/redis-master-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: default-redis-master
  namespace: "default"
  labels:
    app: redis
    chart: redis-12.1.1
    release: default
    heritage: Helm
spec:
  type: ClusterIP
  ports:
    - name: redis
      port: 6379
      targetPort: redis
  selector:
    app: redis
    release: default
    role: master
