---
# Source: redis/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: default-redis
  namespace: "default"
  labels:
    app: redis
    chart: redis-12.1.1
    release: "default"
    heritage: "Helm"
type: Opaque
data:
  redis-password: "NTJtUzd2anRQaQ=="
